/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package control;

import java.awt.Graphics;
import java.util.ArrayList;
import pacman.FiguraGeometrica;
import pacman.*;

/**
 *
 * @author pablo
 */
public class Lienzo extends javax.swing.JPanel implements Runnable{
	private boolean isPlaying;
	private ArrayList<FiguraGeometrica> figurasEstaticas;
	private ArrayList<FiguraGeometrica> figurasDinamicas;

	public void dibujarPared(Graphics lapiz,Pared paredActual){
        if (paredActual.getColorBorde()!=null) {
            lapiz.setColor(paredActual.getColorBorde());
        }
        lapiz.drawRect(paredActual.getX(),paredActual.getY(),
                       paredActual.getWidth(), paredActual.getHeight());
        if (paredActual.getColorRelleno()!=null) {
            lapiz.setColor(paredActual.getColorRelleno());
        }
        lapiz.fillRect(paredActual.getX(),paredActual.getY(),
                       paredActual.getWidth(), paredActual.getHeight());
    }
    
    public void dibujarCirculo(Graphics lapiz,Circulo circuloActual){
        if (circuloActual.getColorBorde()!=null) {
            lapiz.setColor(circuloActual.getColorBorde());
        }
        lapiz.drawOval(circuloActual.getX(), circuloActual.getY(),
                       circuloActual.getRadio(), circuloActual.getRadio());
        if (circuloActual.getColorRelleno()!=null) {
            lapiz.setColor(circuloActual.getColorRelleno());
        }
        lapiz.fillOval(circuloActual.getX(), circuloActual.getY(),
                       circuloActual.getRadio(), circuloActual.getRadio());
    }
	
	/**
	 * Creates new form Lienzo
	 */
	public Lienzo() {
		initComponents();
		this.figurasEstaticas = new ArrayList<>();
		this.figurasDinamicas = new ArrayList<>();
		this.isPlaying = false;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
	
	@Override
	public void paintComponent(Graphics lapiz){
		super.paintComponent(lapiz);
		for(FiguraGeometrica actual:this.getFigurasEstaticas()){
			if(actual instanceof Pared){
				dibujarPared(lapiz, (Pared) actual);
			}
		}
		for(FiguraGeometrica actual:this.getFigurasDinamicas()){
			if(actual instanceof Circulo){
				dibujarCirculo(lapiz, (Circulo) actual);
			}
		}
		
	}
	
	@Override
	public void run() {
		
	}

	/**
	 * @return the isPlaying
	 */
	public boolean isIsPlaying() {
		return isPlaying;
	}

	/**
	 * @param isPlaying the isPlaying to set
	 */
	public void setIsPlaying(boolean isPlaying) {
		this.isPlaying = isPlaying;
	}

	/**
	 * @return the figurasEstaticas
	 */
	public ArrayList<FiguraGeometrica> getFigurasEstaticas() {
		return figurasEstaticas;
	}

	/**
	 * @param figurasEstaticas the figurasEstaticas to set
	 */
	public void setFigurasEstaticas(ArrayList<FiguraGeometrica> figurasEstaticas) {
		this.figurasEstaticas = figurasEstaticas;
	}

	/**
	 * @return the figurasDinamicas
	 */
	public ArrayList<FiguraGeometrica> getFigurasDinamicas() {
		return figurasDinamicas;
	}

	/**
	 * @param figurasDinamicas the figurasDinamicas to set
	 */
	public void setFigurasDinamicas(ArrayList<FiguraGeometrica> figurasDinamicas) {
		this.figurasDinamicas = figurasDinamicas;
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
